sport_parser/khl/urls.py
from django.urls import path
from sport_parser.khl.views import KHLStatsView, KHLTeamView, KHLMatchView, KHLCalendarView, KHLUpdateSeasonView, \
    KHLUpdateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'khl'
urlpatterns = [
    path('stats/', KHLStatsView.as_view(), name='last_stats'),
    path('stats/<int:season_id>', KHLStatsView.as_view(), name='stats'),
    path('team/<int:team_id>', KHLTeamView.as_view(), name='team'),
    path('match/<int:match_id>/', KHLMatchView.as_view(), name='match'),
    path('calendar/<int:season_id>/', KHLCalendarView.as_view(), name='calendar'),

    path('update/season/<int:season>', KHLUpdateSeasonView.as_view()),
    path('update/protocol/', KHLUpdateView.as_view()),

    path('stats/', KHLStatsView.as_view(), name='index_stats'),
    path('team/', KHLTeamView.as_view(), name='index_team'),
    path('match/', KHLMatchView.as_view(), name='index_match'),
    path('calendar/', KHLCalendarView.as_view(), name='index_calendar'),
]

urlpatterns += staticfiles_urlpatterns()

sport_parser/nhl/urls.py
from django.urls import path
from sport_parser.nhl.views import NHLUpdateView, NHLUpdateSeasonView, NHLCalendarView, NHLStatsView, NHLTeamView, NHLMatchView, NHLCalendarApi
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'nhl'
urlpatterns = [
    path('stats/', NHLStatsView.as_view(), name='last_stats'),
    path('stats/<int:season_id>', NHLStatsView.as_view(), name='stats'),
    path('team/<int:team_id>', NHLTeamView.as_view(), name='team'),
    path('match/<int:match_id>/', NHLMatchView.as_view(), name='match'),
    path('calendar/<int:season_id>/', NHLCalendarView.as_view(), name='calendar'),

    path('update/season/<int:season>', NHLUpdateSeasonView.as_view()),
    path('update/protocol/', NHLUpdateView.as_view()),

    path('stats/', NHLStatsView.as_view(), name='index_stats'),
    path('team/', NHLTeamView.as_view(), name='index_team'),
    path('match/', NHLMatchView.as_view(), name='index_match'),
    path('calendar/', NHLCalendarView.as_view(), name='index_calendar'),
]

urlpatterns += staticfiles_urlpatterns()

sport_parser/urls.py
from django.contrib import admin
from django.urls import path, include
from sport_parser.views import index
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('khl/', include('sport_parser.khl.urls')),
    path('nhl/', include('sport_parser.nhl.urls')),
    path('api/', include('sport_parser.api.urls'))
]

urlpatterns += staticfiles_urlpatterns()

sport_parser/core/models.py
import json

from django.db import models
from django.db.models import Q


class AbstractModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class LiveMatches(AbstractModel):
    league = models.CharField(max_length=100)
    match_id = models.IntegerField()


class SeasonModel(AbstractModel):
    id = models.IntegerField(primary_key=True)
    external_id = models.IntegerField(null=True)
    table_data = models.JSONField(null=True, encoder=json.JSONEncoder, decoder=json.JSONDecoder)

    def __str__(self):
        return str(self.id)

    class Meta:
        abstract = True


class TeamModel(AbstractModel):
    season = models.ForeignKey(SeasonModel, on_delete=models.CASCADE, related_name='teams')

    name = models.CharField(max_length=100)
    img = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    arena = models.CharField(max_length=100)
    division = models.CharField(max_length=100)
    conference = models.CharField(max_length=100)

    chart_data = models.JSONField(null=True, encoder=json.JSONEncoder, decoder=json.JSONDecoder)

    @property
    def matches(self):
        return self.season.matches.filter(Q(home_team=self) | Q(guest_team=self))

    def __str__(self):
        return str(self.id)

    class Meta:
        abstract = True


class MatchModel(AbstractModel):
    season = models.ForeignKey(SeasonModel, on_delete=models.CASCADE, null=True, related_name='matches')
    home_team = models.ForeignKey(TeamModel, on_delete=models.CASCADE, related_name='home_matches', null=True)
    guest_team = models.ForeignKey(TeamModel, on_delete=models.CASCADE, related_name='guest_matches', null=True)

    id = models.IntegerField(primary_key=True)
    date = models.DateTimeField(null=True)
    arena = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    viewers = models.IntegerField(default=0)
    status = models.CharField(choices=[
        ('scheduled', 'scheduled'),
        ('finished', 'finished'),
        ('postponed', 'postponed'),
        ('live', 'live'),
        ('game over', 'game over'),
    ], max_length=9, default='scheduled')
    penalties = models.BooleanField(default=False)
    overtime = models.BooleanField(default=False)

    table_data = models.JSONField(null=True, encoder=json.JSONEncoder, decoder=json.JSONDecoder)
    chart_data = models.JSONField(null=True, encoder=json.JSONEncoder, decoder=json.JSONDecoder)
    bar_data = models.JSONField(null=True, encoder=json.JSONEncoder, decoder=json.JSONDecoder)

    def __str__(self):
        return str(self.id)

    class Meta:
        abstract = True


class ProtocolModel(AbstractModel):
    team = models.ForeignKey(TeamModel, on_delete=models.CASCADE, related_name='protocols')
    match = models.ForeignKey(MatchModel, on_delete=models.CASCADE, related_name='protocols')
    season = models.ForeignKey(SeasonModel, on_delete=models.CASCADE, related_name='protocols')

    g = models.IntegerField(null=True, default=0)
    g_1 = models.IntegerField(null=True, default=0)
    g_2 = models.IntegerField(null=True, default=0)
    g_3 = models.IntegerField(null=True, default=0)
    g_ot = models.IntegerField(null=True, default=0)
    g_b = models.IntegerField(null=True, default=0)

    class Meta:
        abstract = True


class LiveMatchModel(AbstractModel):
    match = models.OneToOneField(MatchModel, on_delete=models.CASCADE, related_name='live')

    status = models.CharField(max_length=100, null=True, blank=True)
    team1_score = models.IntegerField(null=True, default=0)
    team2_score = models.IntegerField(null=True, default=0)

    bar_data = models.JSONField(null=True, encoder=json.JSONEncoder, decoder=json.JSONDecoder)

    class Meta:
        abstract = True


class ModelList:
    season_model: SeasonModel
    match_model: MatchModel
    team_model: TeamModel
    protocol_model: ProtocolModel
    live_match_model: LiveMatchModel

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" class="background">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block static %}
    <script type="text/javascript" src="{% static 'js/seasonStats.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css'%}" type="text/css">
    <link rel="icon" href="{% static '/img/favicons/favicon.svg' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/img/favicons/favicon_32_rounded.png'%}">
    {% endblock %}

    {% block script_exec %}
    <script>
    window.onload = function() {
        CONFIG = "{{ config|safe }}"
        if (typeof left_matches !== 'undefined') {
            createMatchFrame('team1', left_matches);
            createMatchFrame('team2', right_matches);
            checkMatches();
        }
        if (typeof live_matches !== 'undefined') {
            createMatchFrame('LiveMatches', live_matches);
        }
        if (typeof hideChart !== 'undefined') {
            hideChart()
        }
        if (typeof initCalendar !== 'undefined') {
            initCalendar()
        }
    }
    </script>
    {% endblock %}

{% block metrika %}
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(8935165, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/8935165" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
{% endblock %}
</head>
<main class="background">

<div>
    {% block background_image %}<img src="{{ background_image }}" alt="bg" class="background_image">{% endblock %}
</div>

<header>
<div id="leftHeaderBlock">
    <a href="/"><img src="/static/img/FA_small_white.webp" alt="logo" class="logo"></a>
     <nav>
         {% block nav %}
         <a href="/">Главная</a>
         {% endblock %}
     </nav>
</div>
<div id="rightHeaderBlock">
    <div class="header">
        {% block header_title %}
        {% endblock %}
    </div>
    {% block right_logo %}
    {% endblock %}
</div>
</header>

<div class="wrapper">
<div class="sidebarLeft">
    {% block left_sidebar %}
    {% endblock %}
</div>

<div class="container">
{% block main_content %}
{% endblock %}
</div>
    <div class="sidebarRight" id='rightSideBar'>
        {% block right_sidebar %}
        {% endblock %}
    </div>
</div>
<footer>
    <div class="wrapper">
        {% block footer %}
        <div>
        <a href="#">About</a>
        <a href="#">Feedback</a>
        <a href="#">Contact Us</a>
        <a href="#">Terms</a>
        <a href="#">Privacy</a>
        <a href="#">Cookies</a>
        </div>
        {% endblock %}
    </div>
</footer>
</main>
</html>

templates/khl_calendar.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}Сезон {{ season }} - {{ title }} - flawlessanalytics{% endblock %}

{% block static %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'css/calendar.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static theme %}" type="text/css">
    <script>
    var season = {{ season|safe  }};
    </script>
    <script type="text/javascript" src="{% static 'js/calendar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/matchFrame.js' %}"></script>
{% endblock %}

{% block nav %}
    {{ block.super }}
    <a href="{{ url_stats }}{{ season }}">Сезоны</a>

{% endblock %}

{% block header_title %}
    <h4>{{ league_title }}</h4>
{% endblock %}

{% block right_logo %}
    <img src="{{ league_logo }}" alt="KHL" class="leagueLogo">
{% endblock %}

{% block left_sidebar %}
        <p>Cезоны:</p>
    <ul>
        {% for season in season_list %}
            <a href="{{ url_calendar }}{{ season }}"><li>{{ season }}</li></a>
        {% endfor %}
    </ul>
{% endblock %}

{% block right_sidebar %}
{% endblock %}

{% block main_content %}
    <h3>Сезон {{ season }}</h3>
    <div class="filter">
        <form class="form" id="calendar_filter" action="{% url 'calendar_api' %}" method="get">
            <p><label for="id_teams">Команда:</label>
                <select name="teams" id="id_teams">
                    <option value="" selected="">---------</option>
                    {% for team in teams %}
                        <option value="{{ team.id }}">{{ team.name }}</option>
                    {% endfor %}
                </select></p>
            <p><label for="id_status">Статус матча:</label>
                <select name="status" id="id_status">
                  <option value="" selected="">---------</option>
                  <option value="scheduled">Запланирован</option>
                  <option value="finished">Завершен</option>
                  <option value="postponed">Отменен</option>
                </select></p>

                <label for="id_ordering">Сортировка:</label>
                <div id="ordering-checkbox" class="ordering-checkbox" onclick="toggleOrdering()">
                    <div>Дата</div>
                </div>
                <select class="ordering-checkbox" name="ordering" id="id_ordering">
                  <option value="date">По возрастанию</option>
                  <option value="-date">По убыванию</option>
                </select>

            <button type="reset" onclick="toggleOrderingAsc()">Сбросить</button>
            <button type="submit">Применить</button>
        </form>
    </div>

    <div class="lastMatches">
        <div class="team1" id="team1">

        </div>
    </div>
{% endblock %}

templates/khl_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FLAWLESS ANALYTICS</title>
    <link rel="stylesheet" href="{% static 'css/index.css'%}" type="text/css">
    <link rel="icon" href="{% static '/img/favicons/favicon.svg' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/img/favicons/favicon_32_rounded.png'%}">

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(8935165, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/8935165" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<meta name="google-site-verification" content="5S3KsXYDJJwniPp5SmGAHav-Ol6zeEFU6HVF9XPYTPA" />
</head>
<body>
<main class="background">
    <div>
        <img src="/static/img/slid_1.webp" alt="background" class="background_image">
    </div>
    <header>
        <a href="/" class="a_logo"><img src="/static/img/FA_small_white.webp" alt="FA_logo" class="logo"></a>
        <div class="name">
            <h4>Flawless Analytics</h4>
        </div>
    </header>

<div class="container">
    <div class="text1">
        <h3>Подробная статистика хоккейных матчей</h3>
        <p>Самая полная статистика хоккейных матчей со всего мира</p>
    </div>

    <div class="league">
        <a href="{% url 'khl:last_stats'%}"><img src="/static/img/KHL.webp" alt="" id="KHL" class="league_button"></a>
        <a href="{% url 'nhl:last_stats'%}"><img src="/static/img/NHL.webp" id="NHL" alt="" class="league_button"></a>
    </div>
</div>
</main>
</body>
</html>

templates/khl_match.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{{ team1.data.name }} - {{ team2.data.name }} - {{ title }} - flawlessanalytics{% endblock %}

{% block static %}
{{ block.super }}
    <script>
    var stats = {{ chart_stats|safe }};
    var left_matches = {{ team1.last_matches|safe }};
    var right_matches = {{ team2.last_matches|safe }};
    var league = "{{ league|safe }}";
    var match_id = {{ match.id|safe }};
    var status = "{{ match.status|safe }}";
    </script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{% static 'js/statCharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/liveMatch.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/matchFrame.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/matchStats.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static theme %}" type="text/css">
{% endblock %}

{% block nav %}
    {{ block.super }}
    <a href="{{ url_stats }}{{ match.season }}">Сезоны</a>
    <a href="{{ url_calendar }}{{ match.season }}">Календарь</a>

{% endblock %}

{% block header_title %}
    <h4>{{ league_title }}</h4>
{% endblock %}

{% block right_logo %}
    <img src="{{ league_logo }}" alt="KHL" class="leagueLogo">
{% endblock %}

{% block left_sidebar %}
{% endblock %}

{% block right_sidebar %}
    <ul class="chartList" id="chartList">
    </ul>
{% endblock %}

{% block main_content %}
    <span id="chart-stat_left"></span>
    <span id="chart-stat_right"></span>
    <div class="teams">
        <div class="team1_info">
            <p class="header_city">Конференция «{{ team1.data.conference }}»</p>
            <p class="header_city">Дивизион {{ team1.data.division }}</p>
            <a href="{{ url_team }}{{ team1.data.id }}"><h4 class="header_title">{{ team1.data.name }}</h4></a>
            <p class="header_city">{{ team1.data.city }}</p>
            <p class="header_city">{{ team1.data.arena }}</p>
        </div>

        <img src="{{ team1.data.img }}" alt="KHL" class="leagueLogo" id="team_logo">

            <div class="score">
                {% language 'ru' %}


                    {% if match.status == 'live' or match.status == 'game over' %}
                        <p id="score_time"></p>
                        <p class="arena" id="arena"></p>
                    {% elif match.status == 'finished' %}
                        <p class="header_city">{{ match.date|date:'j E Y' }}</p>
                        <p id="score_time">{{ team1.score.match }} - {{ team2.score.match }}</p>

                        {% if overtime == True %}
                            <p class="arena" id="score_by_period">ОТ<br>
                                {{ team1.score.p1 }}-{{ team2.score.p1 }}
                                {{ team1.score.p2 }}-{{ team2.score.p2 }}
                                {{ team1.score.p3 }}-{{ team2.score.p3 }}
                                {{ team1.score.ot }}-{{ team2.score.ot }}
                            </p>
                        {% elif penalties == True %}
                            <p class="arena" id="score_by_period">Б<br>
                                {{ team1.score.p1 }}-{{ team2.score.p1 }}
                                {{ team1.score.p2 }}-{{ team2.score.p2 }}
                                {{ team1.score.p3 }}-{{ team2.score.p3 }}
                                {{ team1.score.ot }}-{{ team2.score.ot }}
                                {{ team1.score.b }}-{{ team2.score.b }}
                            </p>
                        {% else %}
                            <p class="arena" id="score_by_period">
                                {{ team1.score.p1 }}-{{ team2.score.p1 }}
                                {{ team1.score.p2 }}-{{ team2.score.p2 }}
                                {{ team1.score.p3 }}-{{ team2.score.p3 }}
                            </p>
                        {% endif %}
                        <p class="arena" id="arena">{{ match.arena }}</p>
                        {% if match.viewers %}
                            <p class="arena" id="viewers">Зрителей: {{ match.viewers }}</p>
                        {%  endif %}
                    {% elif match.status == 'postponed' %}
                        <p class="header_city">{{ match.date|date:'j E Y' }}</p>
                        <p id="score_time" style="font-family: Montserrat, sans-serif; font-size: 80px; padding-top: 0">{{ match.date|time }}</p>
                        <p class="arena" id="postponed">Отменен<br>
                    {% else %}
                        <p class="header_city">{{ match.date|date:'j E Y' }}</p>
                        <p id="score_time" style="font-family: Montserrat, sans-serif; font-size: 80px; padding-top: 0">{{ match.date|time }}</p>
                    {% endif %}

                {% endlanguage %}
            </div>

        <img src="{{ team2.data.img }}" alt="KHL" class="leagueLogo" id="team_logo">

        <div class="team2_info">
            <p class="header_city">Конференция «{{ team2.data.conference }}»</p>
            <p class="header_city">Дивизион {{ team2.data.division }}</p>
            <a href="{{ url_team }}{{ team2.data.id }}"><h4 class="header_title">{{ team2.data.name }}</h4></a>
            <p class="header_city">{{ team2.data.city }}</p>
            <p class="header_city">{{ team2.data.arena }}</p>
        </div>
    </div>


    {% if match.status == 'live' or match.status == 'game over' %}
    {% language 'ru' %}
    <div class="match_stats" id="match_stats"></div>
    {% endlanguage %}
    {% endif %}



{% if match.status == 'finished' %}
    <h3></h3>
    {% language 'ru' %}
<div class="match_stats">
    {% for _, stat in match_stats.items %}
    <div class="match_stat">
        <span class="match_stat_text">{{ stat.long_title }} ({{ stat.short_title }})</span>
        <div class="stat_lines">
            <span class="match_stat_text" style="text-align: right">{{ stat.left_value }}</span>
            <div class="progress_left">
                {% with stat.left_perc as percent %}
                <span class="progress-bar_left" style="width: {{ percent }}%"></span>
                {% endwith %}
            </div>
            <div class="progress_right">
            {% with stat.right_perc as percent %}
                <span class="progress-bar_right" style="width: {{ percent }}%"></span>
            {% endwith %}
            </div>
            <span class="match_stat_text" style="text-align: left">{{ stat.right_value }}</span>
        </div>
    </div>
    {% endfor %}
</div>
    {% endlanguage %}
    {% endif %}

    <h3>Статистика команд в {{ match.season }} сезоне</h3>
    <table class="table_sort">
    <thead>
        <tr>
            {% for name in season_stats.0 %}
            <th>{{ name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for row in season_stats|slice:"1:" %}
        <tr>
        <td onmousedown="middleGotoTeam({{ row.0 }})" onmouseup="gotoTeam({{ row.0 }})" class="urlToTeam">{{ row.1 }}</td>
        {% for stat in row|slice:"2:" %}
            <td align="right">{{ stat }}</td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>


    <div style="display: flex; justify-content: space-between">
        <h3 id="chartTitle1">Все броски</h3><h3 id="chartTitle2">Sh</h3>
    </div>

    <div id="chart" class="charts"></div>

    <h3 id="LastMatchesTitle">Последние матчи</h3>
    <div class="lastMatches">
        <div class="team1" id="team1">

        </div>
        <div class="team2" id="team2">

        </div>
    </div>
{% endblock %}

templates/khl_stats.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load extra_tags %}

{% block title %}Сезон {{ season }} - {{ title }}{% endblock %}

{% block static %}
{{ block.super }}
    <script>
    var left_matches = {{ last_matches|safe }};
    var right_matches = {{ future_matches|safe }};
    var live_matches = {{ live_matches|safe }};
    var GLOSSARY = {{ glossary|safe }};
    </script>
    <script type="text/javascript" src="{% static 'js/matchFrame.js' %}"></script>
    <link rel="stylesheet" href="{% static theme %}" type="text/css">
{% endblock %}

{% block nav %}
    {{ block.super }}
    <a href="{{ url_calendar }}{{ season }}">Календарь</a>
{% endblock %}

{% block header_title %}
    <h4>{{ league_title }}</h4>
{% endblock %}

{% block right_logo %}
    <img src="{{ league_logo }}" alt="KHL" class="leagueLogo">
{% endblock %}

{% block left_sidebar %}
    <p>Cезоны:</p>
    <ul>
        {% for season in season_list %}
            <a href="{{ url_stats }}{{ season }}"><li>{{ season }}</li></a>
        {% endfor %}
    </ul>
{% endblock %}

{% block main_content %}
<h3>СЕЗОН {{ season }}</h3>
    {% language 'ru' %}
        <div style="display: flex; justify-content: space-between">
        <p class="update">Последнее обновление: {{ update }}</p>
        <h3 id="glossButton" onclick="toggleGloss()">Глоссарий</h3>
        </div>
    {% endlanguage %}

    <div class="off" id="glossary">
        {% for key, value in glossary.items %}
        <div>
            <span class="gloss_title">{{ key }}</span><br>
            <span class="gloss_value">{{ value.short }}</span>
        </div>
        {% endfor %}
    </div>

<table class="table_sort">
    <thead>
        <tr>
            {% for name in stats.0 %}
            <th onmouseover="tooltip('{{name}}')" onmouseleave="tooltipHide('{{name}}')">{{ name }}
                {% with glossary|keyvalue:name as value %}
                <div class="tooltip" id="{{ name }}">
                    {{ value.short }}
                </div>
                {% endwith %}
            </th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for row in stats|slice:"1:" %}
        <tr>
        <td onmousedown="middleGotoTeam({{ row.0 }})" onmouseup="gotoTeam({{ row.0 }})" class="urlToTeam">{{ row.1 }}</td>
        {% for stat in row|slice:"2:" %}
            <td align="right">{{ stat }}</td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

{% if live_matches != '{}' %}
    <div style="display: flex; justify-content: space-between">
        <h3>Текущие матчи</h3>
    </div>
    <div class="LiveMatches" id="LiveMatches">
    </div>
{% endif %}

<div style="display: flex; justify-content: space-between">
        <h3 id="LastMatchesTitle">Последние матчи</h3>
        <h3 id="FutureMatchesTitle">Ближайшие матчи</h3>
    </div>

    <div class="lastMatches">
        <div class="team1" id="team1">

        </div>
        <div class="team2" id="team2">

        </div>
</div>

{% endblock %}

templates/ws_update.html
<!-- тут будет текст сообщений -->
<body style="background: black; color: #858585">
    <div id=messages>/</div>
</body>



<script>
    let protocol = 'ws:';
    if (window.location.protocol === 'https:') {
        protocol = 'wss:'
        }

    // открытие соединения с вебсокетом
    const updatews = new WebSocket(
        `${protocol}//${window.location.host}/ws/update_protocol`
    )

    // функция добавления сообщения
    const addUpdateStatus = (message) => {
        document.getElementById('messages').innerHTML =
        document.getElementById('messages').innerHTML + `
        ${message}<br>
        `
        window.scrollTo(0,document.body.scrollHeight);
    }

    updatews.onopen = (event_) => {
        addUpdateStatus('connected to websocket')
    }

    // событие при получении сообщения из вебсокета
    updatews.onmessage = (event_) => {
        const message = event_.data
        addUpdateStatus(message)
    }

    // событие при закрытии соединения
    updatews.onclose = (event_) => {
        addUpdateStatus('update socket close')
        console.error('update socket close')
    }
</script>